services:
  - type: web
    name: gst-reco-pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1